# Generated by Django 5.0.2 on 2024-02-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_rename_products_new_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='myapp2.product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
