# Generated by Django 5.0.2 on 2024-02-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_rename_products_order_products_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products_new',
            new_name='products',
        ),
    ]
